name: Train KMeans Clustering Model

on:
  push:
    branches:
      - main

jobs:
  train:
    runs-on: self-hosted
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install pandas numpy matplotlib seaborn scipy statsmodels scikit-learn
            - name: Execute Script
        run: |
          python train.py  

      - name: Upload Clusters Plot
        uses: actions/upload-artifact@v2
        with:
          name: clusters_plot
          path: clusters_plot.png

      - name: Finalize
        run: |
          echo "Model training completed successfully."
